ZFDEV15122 Fix problem running in go 1.24 projects:
% staticcheck
-: # github.com/zeroflucs-given/charybdis/metadata
vendor/github.com/zeroflucs-given/charybdis/metadata/type_specification.go:60:45: undefined: gocql.TypeMetadata
vendor/github.com/zeroflucs-given/charybdis/metadata/type_specification.go:68:15: undefined: gocql.TypeMetadata (compile)
-: module requires at least go1.24.1, but Staticcheck was built with go1.24.0 (compile)